In [3]:
num = int(input('Enter a number from 0 to 9:'))
if num==3:
  print ('You picked 3')
elif num==6:
    print ('You picked 6')
elif num==9:
  print('You picked 9!')
else:
  print('You havent picked a multiple of 3!')

Enter a number from 0 to 9:7
You havent picked a multiple of 3!


In [4]:
#Maps and Filters
#Map: Takes everything that is passed
#Filter : Gives results based on the condition passed

In [5]:
#Map function

num_var = [1,2,3,4,5]
def pow_func(par):
  return pow(par,par-1)

def my_map_func(the_func, the_iterable):
  res=[]
  for i in the_iterable:
    res.append(the_func(i))
  return res

In [6]:
map_result1 = my_map_func(pow_func,num_var)
print("My map function result is:{}".format(map_result1))

map_result2 = list(map(lambda x : pow(x,x-1),num_var))
print('My In-built function result is:{}'.format(map_result2))

My map function result is:[1, 2, 9, 64, 625]
My In-built function result is:[1, 2, 9, 64, 625]


In [7]:
#Filter 
def cond_func(par):
  return par%2

def my_filter_func(the_func,the_iterable):
  res= []
  for i in the_iterable:
    if the_func(i)==0:
      res.append(i)
    else:
      pass
  return tuple(res)

In [8]:
filter_result1 = my_filter_func(cond_func,num_var)
print('My filter function result is : {}'.format(filter_result1))
filter_result2 = tuple(map(lambda x: x%2==0,num_var))
print('My inbuilt function result is: {}'.format(filter_result2))

My filter function result is : (2, 4)
My inbuilt function result is: (False, True, False, True, False)


In [ ]:
##NumPY

In [ ]:
''' 1) Powerful Linear algebra library 
2) PyData Ecosystem is built on Numpy
3) Numpy is a very fast 
4) It is built on C language '''

' 1) Powerful Linear algebra library \n2) PyData Ecosystem is built on Numpy\n3) Numpy is a very fast \n4) It is built on C language '

In [9]:
import numpy as np

In [10]:
my_list = [1,2,3]

In [12]:
#Array
type(np.array(my_list))

numpy.ndarray

In [13]:
my_matrix = [[1,2,3],[4,5,6]]

In [14]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [27]:
np.logspace(0,20,4)

array([1.00000000e+00, 4.64158883e+06, 2.15443469e+13, 1.00000000e+20])

In [28]:
#Identity Matrix

np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [30]:
#Random values
np.random.rand(6)

array([0.16160616, 0.85167659, 0.69259475, 0.77080023, 0.73563559,
       0.55572379])

In [32]:
np.random.randn(8)

array([ 1.00418716, -0.14193698,  1.2439422 ,  0.51516038, -1.02509142,
        2.10703883, -0.38673316, -0.7772747 ])

In [48]:
np.random.seed(42)
np.random.randint(5,25)

11

In [45]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [37]:
np.random.rand(4)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [49]:
arr = np.arange(30)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
arr.reshape((6,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [55]:
arr.dtype

dtype('int64')

In [ ]:
#Indexing 

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
arr[6]

6

In [58]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
#Broadcasting
arr[0:5] =100

In [62]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [63]:
slice_of_arr = arr[0:6]

In [64]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [65]:
slice_of_arr[:] = 55

In [66]:
slice_of_arr

array([55, 55, 55, 55, 55, 55])

In [67]:
arr

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

In [68]:
copyarr = arr.copy()

In [69]:
copyarr

array([55, 55, 55, 55, 55, 55,  6,  7,  8,  9, 10])

In [70]:
#Axis in numpy
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr_2d.sum()

45

In [73]:
arr_2d.max()

9

In [74]:
arr_2d.min()

1

In [75]:
arr_2d.sum(axis=0)

array([12, 15, 18])

In [76]:
arr_2d.sum(axis=1)

array([ 6, 15, 24])